version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 009160060366.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t cicdrepo .
      - docker tag cicdrepo:latest 009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:latest
      - docker rmi cicdrepo:latest  # Optional cleanup step

artifacts:
  files:
    - '**/*'  # Modify this based on what you need, or remove if not necessary
